# Generated by Django 5.0.7 on 2024-07-18 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carlist',
            name='prices',
            field=models.IntegerField(null=True),
        ),
    ]
