# Generated by Django 5.0.7 on 2024-07-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carlist_prices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carlist',
            name='prices',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
